apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagent-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagent
  template:
    metadata:
      labels:
        app: pagent
    spec:
      containers:
      - name: backend
        image: ghcr.io/ezragubbay/pagent-backend:latest
        ports:
        - containerPort: 8000
        
        # Tell Python where to find the key file
        env:
        - name: FCM_SECRETS_DIR
          value: "/app/secrets"

        # Mount the secret as a folder inside the container
        volumeMounts:
        - mountPath: "/app/storage/temp_storage"
          name: uploads-volume
        - mountPath: "/app/secrets"  # This folder will be created automatically
          name: firebase-secret-vol
          readOnly: true             # Security best practice

        envFrom:
        - secretRef:
            name: app-secrets
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
      
      # Define the Volume using the K8s Secret
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: firebase-secret-vol
        secret:
          secretName: firebase-secret 

      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pagent-backend
spec:
  type: NodePort
  selector:
    app: pagent
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080